src/pages/App.tsx

For example, press <kbd>⌘⇥</kbd> after you start, the timer should stop.

Stop the timer when window defocuses (e.g. users turn to other apps or tabs)

---

src/components/AppSettings.tsx
src/components/Word/index.tsx
src/hooks/usePronouncation.ts
src/icon.ts
src/pages/Typing/PronunciationSwitcher/index.tsx
src/pages/Typing/Switcher/index.tsx
src/pages/Typing/hooks/usePronunciation.ts
src/pages/Typing/hooks/useSwitcherState.ts
src/pages/Typing/index.tsx

**尝试给项目增加一个单词发音的功能**
Hi, developers:
非常喜欢这个项目！我花了一些时间写了单词发音功能的雏形。调用了有道词典的发音API，看起来效果不错。
Hope you like it.

尝试增加单词发音功能

---

public/dicts/java-arraylist.json
public/dicts/java-character.json
public/dicts/java-hashmap.json
public/dicts/java-linkedlist.json
public/dicts/java-string.json
public/dicts/java-stringBuffer.json

Add some java  api docs

---

src/pages/Gallery/ChapterGroup.tsx
src/pages/Gallery/DictionaryCard.tsx
src/pages/Gallery/DictionaryGroup.tsx
src/pages/Gallery/index.tsx

词典章节切换页面滚动的时候，词典选择和章节选择这两个标题会遮挡住后面的内容，不知道是刻意的还是没有注意到，我看着怪怪的，大致改了一下。

fix(pages/Gallery):修改滚动时标题和内容重叠的问题

---

src/pages/Typing/index.tsx

修复 dict 中重复（相邻）字段导致的卡死，比如 
```
$ head public/dicts/BEC_2_T.json 
[
{ "name": "pharmacy", "trans": ["药房；配药学，药剂学；制药业；一批备用药品"], "usphone": "'fɑrməsi", "ukphone": "'fɑːməsɪ" },
```
把 pharmacy 单词复制一遍，两个连续的相同单词会造成页面卡住。
改了 key 的逻辑，加上了 order 序。

handle duplicated word

---

src/utils/utils.ts

; [ ] \ /
实际使用过程中，这些在键盘字母输入右侧的键也可能会被误输入。
而目前这些键并未被加入合法输入列表中，这样会导致即使误输入了这些键，应用并没有报错，从而会造成错误的肌肉记忆，所以特此增加这些键。

feat(Letter): 增加对更多键盘输入的支持

---

src/components/Modals/index.tsx
src/components/Tooltip/index.tsx
src/pages/Typing/Switcher/index.tsx
src/pages/Typing/index.tsx

调整词典入口下方 hint 位置，与右边其他按钮的 hint 垂直位置对齐，以保证视觉效果一致性
调整前：
调整后：

封装 Tooltip 组件

---

src/components/Word/Letter/index.tsx
src/components/Word/index.tsx
src/hooks/usePronunciation.ts
tailwind.config.js

Using underscore (`_`) as the replacement of spaces is quite misleading. This PR intends to use the so-called “explicit space”  (␣) character, which is a common practice in many places. This PR also adds special styles to explicit space characters.
Here is a preview of all possible situations.

fix: use explicit space characters instead of underscores

---

src/components/Speed/InfoBox.tsx

`flex-grow` gives different width to these info boxes which will shake when the timer starts. Switch to `flex-1` will fix this issue.

fix: InfoBox will no longer shake

---

src/pages/Typing/index.tsx

之前有提到，章节末尾计数不正常：[正确词数计数问题 \#236](https://github.com/Kaiyiwing/qwerty-learner/issues/236)，
调整了一下顺序，提升优先级

fix: 修复章节切换时数据未更新

---

src/hooks/usePronunciation.ts
src/icon.ts
src/pages/Typing/Switcher/index.tsx
src/pages/Typing/hooks/useSwitcherState.ts
src/store/AppState.tsx

增加循环播放单词的功能
开启功能后，该单词会循环播放，直到用户拼写对单词进入下一个单词拼写才会停止播放

feat: add soundLoop (#244)

---

src/components/ResultScreen/index.tsx

Added max-width to resultscreen for better outlook on ultra-wide screens

style: add max-width for summary page

---

src/components/Word/index.tsx

将playKeySound从输入（onKeyDown）后转移到判对后（useLayoutEffect）。
这么做一是减少了playKeySound call的情况，二是onKeyDown是监听英语输入的功能，如果想要支持多语言，onKeyDown需要被抽离到子组件中，所以需要尽量精简。
ps：我发现多语言支持一下做完对我来说太难了，打算尽量拆分成一步步的小更新Orz

refactor: move playKeySound call to judging part

---

public/dicts/PETS_3.json
src/resources/dictionary.ts

[全国英语等级考试(Public English Test System, 简称PETS)](https://pets.neea.edu.cn/)是教育部教育考试院（原教育部考试中心）负责设计并实施的全国性英语水平考试体系。PETS 主要面向自考、成考或已毕业的社会人员。
* dict: 支持 PETS-3 词汇
* dict: 补充词汇「美音」、「英音」音标

dict: add「Public English Test System (PETS-3)」high-frequency dictionary

---

Dockerfile
docker-compose.yaml

默认服务监听端口和镜像的expose端口不一致，导致启动容器后访问不了；

add --host option to yarn start and set port expose

---

index.html
src/components/Footer/index.tsx
src/components/Header/index.tsx
src/components/StarCard/index.tsx
src/index.css
src/pages/Gallery-N/DictRequest.tsx
src/pages/Gallery-N/Dictionary.tsx
src/pages/Gallery/ChapterButton.tsx
src/pages/Gallery/DictionaryCard.tsx
src/pages/Typing/components/PronunciationSwitcher/index.tsx
src/pages/Typing/components/ResultScreen/WordChip.tsx
src/pages/Typing/components/ResultScreen/index.tsx
src/pages/Typing/components/Setting/DataSetting.tsx
src/pages/Typing/components/Setting/index.tsx
src/pages/Typing/components/ShareButton/SharePicDialog.tsx
src/pages/Typing/components/SoundSwitcher/index.tsx
src/pages/Typing/components/Switcher/index.tsx
src/pages/Typing/components/WordPanel/components/SoundIcon/index.tsx
src/pages/Typing/index.tsx

**Goal**: get full marks in SEO and a10y from [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview/).
**Change logs**
- Add `<meta charset />` tag.
- Add `title` or `aria-label` for links, button, and icons.
- Add `alt` to images and icons.
- Add `type` to buttons.
- Improve text contrasts.
- Improve color and shadow of the header.
**Before**
**After**
The logo and start button gain a stronger contrast, which is more user-friendly for visually impaired users. I also changed  the grayish shadow so that it fits the theme color.

refactor: improve SEO and a11y

---

public/dicts/Top1500NounWords.json
public/dicts/top2000words.json
src/resources/dictionary.ts

trans 部分由chatGPT生成
> 除了2265个常用的单词以外，还有1524个名词。但是1144个单词常常作为名词使用，而其他380个单词属于不同的类型，它们也可以作为名词使用。例如：单词"play"是一个动词，如"My kids are going outside to play."然而，它也可以作为一个名词使用，如 "I am going to watch a play."
> 由于单词的多义性 ，我们首先按名词的频率来进行排序，然后再按“名词+其他类型”的频率来进行排序，最后按“其他类型+名词”的频率进行排序
来源：[top-1500-nouns](http://www.talkenglish.com/vocabulary/top-1500-nouns.aspx)

新增一本词典，1500个名词按着使用频次排列

---

src/pages/Typing/components/Switcher/index.tsx

fix: https://github.com/Kaiyiwing/qwerty-learner/issues/376
据所使用的 react-hotkeys-hook [文档](https://react-hotkeys-hook.vercel.app/docs/documentation/useHotkeys/basic-usage#multiple-hotkeys)所示,部分快捷键无法覆盖:
将快捷键由 `ctrl + t` 修改为 `ctrl + shift + v` 此处 `v` 解释与英文保持一致, `visible`
gpt 认为 `ctrl + c` 也是可行的, 解释为 `chinese`

fix: zh visibility hotkey

---

src/pages/Typing/components/WordPanel/components/Translation/index.tsx
src/pages/Typing/components/WordPanel/index.tsx

- 开始练习后暂停时为 “任意键开始” 提示字样添加背景模糊遮罩层而不是直接替换单词内容
- 开始练习后将提示字样中的 “开始” 替换为 “继续”
https://github.com/Kaiyiwing/qwerty-learner/issues/480

feat: add a blurred mask during pause and display "继续" instead of "开始".

---

src/hooks/usePronunciation.ts
src/utils/romajiToHiragana.ts

罗马字转平假名，对应表写在了同一个文件内，简单测试了下没什么问题。
转换逻辑来源：https://github.com/andree-surya/moji4j

fix: fix the Japanese pronunciation wrong problem(#456)

---

src/pages/Typing/components/WordPanel/index.tsx

fix: "Press any key" style override

---

src/hooks/usePronunciation.ts
src/pages/Typing/components/PrevAndNextWord/index.tsx
src/pages/Typing/components/WordPanel/index.tsx

有时候可能网络不好或网络波动，导致单词读音并未加载完成时，用户已经打完(或接近打完)才会开始播放，针对这一点引入了**预加载**功能

feat: add prefetch next word sound

---

src/pages/Typing/components/WordPanel/components/WordSound/index.tsx

fix: https://github.com/Kaiyiwing/qwerty-learner/issues/491
Disable pronunciation in non-typing state. Currently, it pronounces during certain non-typing states, including page refreshing, dictionary switching, or the `Ctrl+J` hotkey.

fix: disable pronunce at non-typing state

---

src/components/Header/index.tsx

bug fix: 修复按任意键继续遮罩层挡住了顶部选择框的问题

fix: 修复按任意键继续遮罩层挡住了顶部选择框的问题

---

src/components/Drawer/index.tsx
src/components/StarCard/index.tsx
src/pages/Typing/components/WordPanel/index.tsx

#506  给Header添加了z-index, 会导致顶部的Header显示在左侧单词列表和提示收藏的提示框之上
修改了Drawer和StarCard的z-index

fix: set a higher z-index to Drawer and StarCard to prevent Header floating onto them

---

public/dicts/Longman_Communication_3000.json
src/resources/dictionary.ts

The **Longman Communication 3000** is a list of the 3000 most frequent words in both spoken and written English, based on statistical analysis of the 390 million words contained in the Longman Corpus Network – a group of corpuses or databases of authentic English language. The Longman Communication 3000 represents the core of the English language and shows students of English which words are the most important for them to learn and study in order to communicate effectively in both speech and writing.
Analysis of the Longman Corpus Network shows that these 3000 most frequent words in spoken and written English account for 86% of the language. This means that by knowing this list of words, a learner of English is in a position to understand 86% or more of what he or she reads. Of course, …

feat(dicts): add Longman Communication 3000

---

src/pages/Gallery-N/DictionaryWithoutCover.tsx

| Before | After |
|--------|--------|
| <img width="923" alt="image" src="https://github.com/Kaiyiwing/qwerty-learner/assets/125171539/1dc6e9b5-fb9f-4141-9040-47cdd83b77d5"> | <img width="929" alt="image" src="https://github.com/Kaiyiwing/qwerty-learner/assets/125171539/092c8af5-95a0-4dc8-8c18-cf0ac7cefb14"> |

fix: dict gallery card text trunacte style

---

src/components/StarCard/index.tsx

StarCard会使手机访问qwerty learner时的界面布局更加混乱，并且考虑到应该不会有用户在手机上无法使用的情况下收藏，也许可以hidden掉。
before:
after:

Improve mobile user interface

---

public/dicts/JapVocabList.N1.json
public/dicts/JapVocabList.N2.json
public/dicts/JapVocabList.N3.json
public/dicts/JapVocabList.N4.json
public/dicts/JapVocabList.N5.json
public/dicts/Jap_High-Frequency_N1.json
public/dicts/Jap_High-Frequency_N2.json
public/dicts/Jap_High-Frequency_N3.json
public/dicts/Jap_High-Frequency_N4N5.json
public/dicts/Japanesebasicword.json

修复日语的所有词典，本人是日语的高分玩家，确定每一个词典都是敲过的并将我能力以内能改的词典进行了修复

Fix jpa dict

---

src/pages/Typing/components/WordPanel/components/Word/index.tsx

为了使浏览器正确显示字体（尤其对于日文），所以我认为应该正确在显示文字的部分的标签上加上lang属性。

fix: missing language tags

---

Dockerfile
public/default.conf

1. 解决 docker 构建镜像, node 版本过低的导致错误
```bash
=> ERROR [7/8] RUN yarn install                                                                                78.5s
------
> [7/8] RUN yarn install:
0.478 yarn install v1.22.19
0.564 [1/4] Resolving packages...
0.945 [2/4] Fetching packages...
77.30 error daisyui@3.5.1: The engine "node" is incompatible with this module. Expected version ">=16.9.0". Got "14.21.3"
77.30 error Found incompatible module.
77.30 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
Dockerfile:20
--------------------
18 |     RUN npm install yarn -g --force
19 |     
20 | >>> RUN yarn install
21 |     
22 |     COPY . .
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn install" did not complete successfully: …
```

fix: 解决镜像构建错误;优化镜像大小

---

README.md
scripts/install.ps1

添加了`install.ps1`脚本
Windows用户拉取代码后，可在powershell/pwsh/ 中执行该脚本。
脚本会检测是否安装了node，如果没有会使用winget安装。
安装完成后会自动还原依赖并运行程序，并自动打开浏览器。
实现一键安装、运行、打开程序。

添加windows下一键安装和运行脚本

---

src/pages/Typing/components/WordPanel/components/Word/index.tsx

operation：在鼠标hover的时候，才会把单词显示出来；
question： 有没有快捷键？
reason: 问这个问题的目的，我在练习单词的时候，双手都聚焦在键盘上，使用鼠标有点浪费时间了~
done：针对该问题，已经做了优化，仅在【开启】默写模式下，才会进行监听，长按Tab显示，松开恢复~
老师再也不担心我用鼠标或者ctrl+v浪费时间了~

feat: mouse hover support extension when hidden word

---

public/dicts/YiLin_1.json
src/resources/dictionary.ts

由于少了译林版教材，因此尝试补了一下，方便按照教学顺序来背单词。

添加译林版高中必修1所有单词

---

README.md
scripts/install.sh

在浏览此项目时，发现了有人为此项目书写了适用于`Windows`的自动安装运行脚本。
因此，我为`MacOS`书写了一个几乎相同功能脚本，并与`Windows`版放在了同一目录下。
此脚本中的`node.js`安装依赖于`homebrew`而不是`winget`，但是主体逻辑完全相同。
此脚本中的绝大部分内容也适用于`Linux`系统，但是由于包管理器以及一些启动指令的不同，无法通用。
对应的README已经修改好，希望此仓库的管理者可以采纳这个脚本。
~*毕竟Windows有的，我们Mac怎么能没有呢？*~

Create Install.sh for MacOS

---

src/pages/Typing/components/WordPanel/components/Word/index.tsx

现有的tips位置，新用户可能不知道是在选择美英发音菜单里面。导致不知道支持快捷键朗读

feat: add sound hotkey tooltip

---

src/pages/Typing/components/ResultScreen/index.tsx

resultScreen z-index hierarchy issue fixes

fix: ResultScreen z-index level

---

src/pages/Typing/components/WordList/index.tsx

ListTooltip z-index level issue fixes

fix: ListTooltip z-index level

---

src/hooks/usePronunciation.ts

**问题描述：**
一直困扰了好久，自动播放声音时，总会自动误触发下载插件：
**环境：**
- Windows 10
- chrome 
- 浏览器 Edge （版本 122.0.2365.92 (正式版本) (64 位)）
- FireFox 124.0.1 (64 位)
会误触发的下载插件有
NeatDownloadManager （1.4.24） [https://www.neatdownloadmanager.com/index.php/en/](url) 
Internet Download Manager （6.24） [https://www.internetdownloadmanager.com/?v=642b7](url)
相关issues:
#577 
**修改内容：**
1. 修改   link 标签为  audio 标签
2. 设置属性 尽可能避免误触发下载插件（软件） （GPT 说的）
audio.crossOrigin = 'anonymous'
audio.style.display = 'none'
**修改后测试**
| 软件名称               | 触发情况     |
|-----------------------|--------------|
| NeatDownloadManager   | 正常无误触发 |
| Internet Download Manager | 正常无误触发 |
| Edge                  | 正常无误触发 |
| FireFox               | 正常无误触发 |
| 迅雷                   | 正常无误触发 |
|Chrome | 正常无误触发|
**以上环境回归无引入新问题，声音播放正常**

更换 link 为 audio 防止触发下载事件

---

src/pages/Typing/components/DictChapterButton/index.tsx

产生bug的原因是：当 Listbox 获取焦点时，按下空格键会触发 Listbox 的默认行为；
我们通过onKeyDown 来阻止空格键的默认行为

fix: 解决输入空格导致下拉框启用的问题

---

src/pages/ErrorBook/RowDetail/index.tsx

This Pull Request addresses an issue in the ErrorBook `RowDetail` component where the `WordPronunciationIcon` was not receiving the correct props, resulting in an "undefined" sound being played for all words.
- Added the missing `lang` prop to the `WordPronunciationIcon` component, ensuring that the correct language is used for pronunciation.
- Corrected the `word` prop type to match the expected structure in `WordPronunciationIcon`.
- Verified that the pronunciation feature now functions correctly, playing the appropriate sound for the selected word.

fix(error_book): correct WordPronunciationIcon props for pronunciation functionality

---

README.md

Remove trailing whitespace after links and line breaks to improve markdown consistency

style: remove trailing whitespace in README.md

---

package.json
src/pages/ErrorBook/DropdownExport.tsx
src/pages/ErrorBook/ErrorRow.tsx
src/pages/ErrorBook/index.tsx
yarn.lock

feat: Export the wrong question book
