RealKai42/qwerty-learner

src/pages/Typing/index.tsx

原来的交互不够统一，应该是手误。改成了
- Enter -> 下一章节/重置到第一章节
- Shift+Enter -> 重复本章节

fix, Enter to 下一章节/重置到第一章节, Shift+Enter to 重复本章节

---

src/utils/utils.ts

修复warnings
https://github.com/Kaiyiwing/qwerty-learner/pull/89#issuecomment-788644114

fix: unnecessary escape

---

.travis.yml
package.json

Add test for warnings like these into Travis: https://github.com/Kaiyiwing/qwerty-learner/pull/89#issuecomment-788644114
https://github.com/Kaiyiwing/qwerty-learner/pull/91#issuecomment-788715662
e.g.

test: 增加 ESLint 测试

---

src/components/Phonetic/index.tsx

fix(Phonetic): fix phonetic color in dark mode

---

package.json
yarn.lock

I’d like Windows users to have a test. 🙋‍♂️
P.S. [cross-env](https://www.npmjs.com/package/cross-env) is a quite popular package.

fix: set environment variables with cross-env

---

docs/README_EN.md

[👀 Preview](https://github.com/Kaiyiwing/qwerty-learner/blob/docs/readme-en/docs/README_EN.md)

Add English translation of README.md

---

src/icon.ts
src/pages/Typing/Switcher/index.tsx
src/pages/Typing/hooks/useSwitcherState.ts
src/pages/Typing/hooks/useWordList.ts
src/pages/Typing/index.tsx
src/store/AppState.tsx

Resolves [qwerty-learner#128 (comment)](https://github.com/Kaiyiwing/qwerty-learner/issues/128#issuecomment-889004292)

feat: shuffle words in chapters

---

Dockerfile
docker-compose.yaml

新增docker-compose一键部署脚本

---

src/pages/Typing/Progress/index.tsx
src/pages/Typing/index.tsx
tailwind.config.js

added progress bar to show users' progress while typing one chapter

feat: add progress bar

---

package.json
src/components/ResultScreen/ConclusionBar.tsx
src/components/ResultScreen/RemarkRing.tsx
src/components/ResultScreen/WordChip.tsx
src/components/ResultScreen/index.tsx
src/components/Speed/index.tsx
src/components/Word/index.tsx
src/icon.ts
src/index.css
src/pages/Typing/index.tsx
yarn.lock

Still in progress, remaking UI.

Remake the summary page

---

public/dicts/GaoKao_3500.json

fix: replace unparseable char in GaoKao_3500

---

public/dicts/OxfordVocabulary_juniorMiddleSH.json
src/resources/dictionary.ts

Added "Oxford Shanghai Edition Junior High School English Vocabulary" to dictionaries.
#293

feat: add SHjuniormiddleOxford dictionary

---

src/pages/Typing/index.tsx

There is still some logic that needs to be optimized.

Fix dictation switch between chapters

---

public/dicts/GaoKao_3500.json

fix: replace abnormal char " ' " in GaoKao3500

---

src/components/Word/index.tsx

Added an if statement to prevent multiple calls to playKeySound during typing, which would cause the sound to increase incorrectly.

fix: fix key sound increasing bug

---

src/components/StarCard/index.tsx
src/index.tsx
src/pages/Typing/index.tsx
src/store/index.ts
tsconfig.json

1. 增加 prod 和 dev 环境区分，方便测试
2. 修改 StatCard 倒计时为 5s
3. 改为在加载网站时提示用户进行收藏

feat: modify StarCard logic

---

src/icon.ts
src/pages/Typing/components/CurrentWord/components/HiddenTextarea/index.tsx
src/pages/Typing/components/CurrentWord/components/Word/index.tsx
src/pages/Typing/components/CurrentWord/index.tsx
src/pages/Typing/components/PronunciationSwitcher/index.tsx
src/pages/Typing/components/ResultScreen/WordChip.tsx
src/pages/Typing/components/ResultScreen/index.tsx
src/pages/Typing/components/Speed/index.tsx
src/pages/Typing/components/Switcher/index.tsx
src/pages/Typing/hooks/useWordList.ts
src/pages/Typing/index.tsx
src/pages/Typing/store/index.ts
src/store/index.ts

1. 重构 Typing page 的状态管理逻辑
2. 使用隐藏的 textarea 来接收用户的键盘输入，为未来的功能做铺垫

refact: reactor state logic of Typing page & word comment

---

src/pages/Typing/components/PronunciationSwitcher/index.tsx
src/pages/Typing/components/ResultScreen/index.tsx
src/pages/Typing/hooks/useWordList.ts
src/store/index.ts

1.  fix show nextChapter when is lastChapter
2. fix change the pronunciation state when chapter change

fix: fix show nextChapter when is lastChapter

---

package.json
src/components/Footer/index.tsx
src/vite-env.d.ts
vite.config.ts
yarn.lock

feat: show the latest commit hash at the footer

---

src/components/InfoPanel/index.tsx
src/pages/Typing/components/ResultScreen/index.tsx

fix: timeString

---

src/components/StarCard/index.tsx
src/pages/Typing/components/Switcher/index.tsx

1.Fix typo in Header from "释意" to "释义"
2.Add dark mode compatibility to certain text in StarCard

fix: correct some text

---

public/dicts/Child_code.json
src/resources/dictionary.ts

feat: 增加了少儿编程

---

public/dicts/top2000words.json
src/resources/dictionary.ts

追加了1本词典：The top 2000 words with the highest frequency ，[来源](https://www.talkenglish.com/vocabulary/top-2000-word-families.aspx)
这本词典与考试关系不大，更多是英语交流和阅读 中的频次，因此比较实用和基础。
trans部分没有解释，而是体现了 word的词性。但也很好，不然怎么解释 the 也是个问题。

add dict top 2k words

---

src/components/Footer/index.tsx
src/components/InfoPanel/index.tsx
src/index.css
src/pages/Gallery-N/DictRequest.tsx

refactor: improve the color of button at info panel footer

---

src/pages/Gallery-N/CategoryDicts.tsx
tailwind.config.js

外观上的小问题：
词典页面所使用的响应式设计为默认值，导致小卡片重叠。
- 修改了 tailwind 配置中分辨率 min-width 的值。

fix: edited screen breakpoint range

---

src/pages/Typing/components/Setting/AdvancedSetting.tsx
src/pages/Typing/components/WordPanel/components/Word/Letter.tsx
src/pages/Typing/components/WordPanel/components/Word/index.tsx
src/store/index.ts

close #381 
1. 增加了鼠标hover单词后现身正确的单词

feat: add hover show word

---

src/pages/Typing/components/ShareButton/SharePicDialog.tsx
src/pages/Typing/components/Speed/index.tsx

opacity-45 没有在tailwind config里定义, 透明样式未生效

fix: self-defined opacity value not applied

---

src/pages/Typing/components/StartButton/index.tsx
src/pages/Typing/index.tsx

add restart button when hover start/pause

---

.vscode/settings.json
src/hooks/useSpeech.ts
src/pages/Typing/components/PronunciationSwitcher/index.tsx
src/pages/Typing/components/Setting/SoundSetting.tsx
src/pages/Typing/components/WordPanel/components/Translation/index.tsx
src/store/index.ts

Fixes #314 
Addresses #285 
**Browser compatibility:**
[Web Speech API - SpeechSynthesis - Web APIs | MDN](https://developer.mozilla.org/zh-CN/docs/Web/API/Web_Speech_API#api.speechsynthesis)

feat: read out translation by web speech api

---

src/index.css
src/pages/Typing/components/WordList/WordCard.tsx
src/pages/Typing/components/WordPanel/components/Phonetic/index.tsx
src/pages/Typing/components/WordPanel/components/Translation/index.tsx
src/pages/Typing/components/WordPanel/components/Word/index.tsx

style: update user select

---

src/pages/Gallery-N/ChapterList/ChapterRow.tsx

fix: 修复了章节选择的时候，如果选择的不是第一个 第一个radio 会看不见问题

---

src/pages/Typing/components/PronunciationSwitcher/index.tsx

fix: pronunciation button adapt to the content width

---

.github/workflows/cr.yml

1.Go to the repo homepage which you want integrate this bot
2.click settings
3.click actions under secrets and variables
4.Change to Variables tab, create a new variable OPENAI_API_KEY with the value of your open api key (For Github Action integration, set it in secrets)
我目前设置的MODEL是3.5的，大佬有gpt4.0的key可以换成4.0的~

Feature  GitHub workflows添加gpt codereview

---

public/dicts/ai_for_science.json
public/dicts/ai_machine_learning.json
src/resources/dictionary.ts

根据：https://github.com/jiqizhixin/Artificial-Intelligence-Terminology-Database/tree/master
添加了：
专项领域篇（仅收录对应领域术语）
[机器学习（Machine Learning）篇](https://github.com/jiqizhixin/Artificial-Intelligence-Terminology/blob/master/section/Machine%20Learning.md)
[AI for Science 篇](https://github.com/jiqizhixin/Artificial-Intelligence-Terminology/blob/master/section/AI%20for%20Science.md)

Add artificial intelligence

---

docs/README_EN.md

Fix typo in README_EN.md

---

src/pages/Typing/components/WordList/WordCard.tsx
src/pages/Typing/components/WordList/wordcard.module.css

Allow clicking to make a word sound when opening the word list of the current chapter
I think this feature is needed
`https://github.com/Kaiyiwing/qwerty-learner/assets/57334674/8987f50c-9150-4ee4-97b1-3423abf853d4`

feat: word list click make word sound

---

src/utils/index.ts

擴充禁止按鍵集合，避免音量鍵、特殊按鍵誤按。
-- Dalufishe 到此一遊 --

update: expand banned key

---

public/dicts/YiLin_1.json
src/resources/dictionary.ts

修复部分单词无法打出的问题

---

public/dicts/self-study_English3.json
src/resources/dictionary.ts

Add complete words for Self-study English II.

---

public/dicts/self-study_English1.json

Fix self-study_English1.json

---

src/pages/Typing/components/DictChapterButton/index.tsx
src/pages/Typing/index.tsx
src/pages/Typing/store/index.ts

Add a drop bar at nav bar to select chapter conveniently

feat: change chapter at nav bar

---

src/resources/dictionary.ts

外研五年级上下册id重了
https://github.com/RealKai42/qwerty-learner/assets/6197922/ee478fd2-ec5c-4ba9-9ff2-dcefe3a6789f

fix: dict id

---

README.md

Hope can help everyone deploy quickly
https://github.com/RealKai42/qwerty-learner/issues/733

docs: update README, add deploy to vercel

---

public/dicts/IELTS_XDF_7000.json
src/resources/dictionary.ts

添加 新东方 雅思词库  《100个句子记完7000个雅思单词》

@feat (add dict):  新东方 100个句子记完7000个雅思单词

---

.vscode/settings.json

plugin "typescript-plugin-css-modules" needs these two configurations.

chore(config): Update settings.json

---

public/dicts/NCE_1.json

fix: 修复新概念英语-1里的一些错误单词

---

public/dicts/HeQiong_IELTS.json
public/dicts/TOEFL_ZhangHongYan.json
public/dicts/self-study_English2.json

fix:https://github.com/RealKai42/qwerty-learner/issues/813

fix: remove invalid entries and correct spelling in dictionary files

---

README.md
docs/README_JP.md

I created Japanese translated README.

docs: add Japanese README

---

public/dicts/beijing_junior_high_school.json

fix(public-dicts): 修正app和application的定义

---

public/dicts/2025KaoYanHongBaoShu.json

fixed 2025kaoyanhongbaoshu
café --> cafe

fix: fixed 2025kaoyanhongbaoshu

---

public/dicts/IELTSLiuHongbo538.json

there are some words that are spelled wrong

fix spelled wrong words

---

README.md
scripts/pre-check.ps1
scripts/pre-check.sh

- Add a section about project runtime and environment preparation to the README document
- Add 'pre-check' to 'scripts' to ensure you have the required environment

docs(readme): Enhance README and add environment check scripts

---

public/dicts/Cambridge_JOIN_IN.json
src/resources/dictionary.ts

添加《剑桥小学英语 JOIN IN》。
closed #901

feat: add 剑桥 JOIN IN
